font_size 12
copy on select yes
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

foreground d1d5e3
background 414457

# uncomment the line below if you didnt set up transparency in Hyprland or your DE/WM
# window_opacity = 0.78
