general {
	disable_loading_bar = true
	hide_cursor = true
}

background {
	monitor =
	path = /path/to/ur/wallpaper.png
	blur_passes = 2
	blur_size = 4
}

input-field {
	monitor =
	size = 250, 50
	outline_thickness = 2
	dots_size = 0.3
	dots_spacing = 0.15
	dots_center = true
	outer_color = #414457
	inner_color = #414457
	font_color = #e1e5f3
	fade_on_empty = false
	placeholder_text = <i>Password?</i>
	hide_input = false
	position = 0, -20
	halign = center
	valign = center
}

label {
	monitor =
	text = cmd[update:1000] echo "$TIME"
	color = #e1e5f3
	font_size = 100
	font_family = JetBrains Mono
	position = 0, 150
	halign = center
	valign = center
}
