[General]
background=#414457
textColor=#d1d5e3
fontSize=14
cornerRadius=10
fontFamily="Adwaita Sans"

# Make sure you have the Adwaita Sans font installed, otherwise, use your desired font.

# To install Adwaita Sans, run in your terminal this command: sudo pacman -S adwaita-fonts
# To apply and use the font, install GNOME tweaks: sudo pacman -S gnome-tweaks
# Applying the font: gsettings set org.gnome.desktop.interface font-name "Adwaita Sans 11"
# You can also open the Tweaks app by itself, open it with your app launcher, go to Fonts and select Adwaita Sans.
