[background]
type = "wallpaper"
# color = "414457"
# uncomment the line above if type = "color"
# path = /path/to/ur/wallpaper.png
# uncomment the line above and add your wallpaper path if type = "wallpaper"
blur = 9

[clock]
enabled = true
time_format = "%H:%M:%S"
date_format = "%D, %M, %Y"
time_size = 64
date_size = 18
color = "#e1e5f3"

[password]
placeholder = "Password?"
box_color = "#606580"
text_color = "#e1e5f3"
border_color = "#a0a5f5"
border_width = 2
circle_indicator = true

[widgets]
battery = true                     # Mostra a porcentagem de bateria atual
weather = false                    # Oculta/mostra informações de clima local
now_playing = true                 # Mostra a mídia atual em reprodução via MPRIS (Spotify, Playerctl)
caps_lock = true                   # Exibe um aviso se o Caps Lock estiver ativado
avatar = true                      # Exibe a foto do seu usuário do Linux (~/.face)
username = true                    # Exibe o seu nome de usuário embaixo do avatar
